2024-02-23 15:36:14,781 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-23 15:36:14,781 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Configure stats pid to 26316
2024-02-23 15:36:14,783 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Loading settings from C:\Users\erika\.config\wandb\settings
2024-02-23 15:36:14,783 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Loading settings from c:\Users\erika\Desktop\Exjobb\repo\base\wandb\settings
2024-02-23 15:36:14,783 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-23 15:36:14,783 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-23 15:36:14,783 INFO    MainThread:26316 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\erika\Desktop\Exjobb\repo\base\wandb\run-20240223_153614-1qjdnvgj\logs\debug.log
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\erika\Desktop\Exjobb\repo\base\wandb\run-20240223_153614-1qjdnvgj\logs\debug-internal.log
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:init():566] calling init triggers
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 32, 'num_heads': 8, 'num_encoders': 2, 'emb_dim': 128, 'ff_dim': 128, 'lr': 0.001, 'weight_decay': 0.1, 'max_seq_len': 51, 'vocab_size': 472, 'num_parameters': 1277144}
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 1t76jyu0
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_run.py:_finish():1970] finishing run strompfel/NCBI/1t76jyu0
2024-02-23 15:36:14,787 INFO    MainThread:26316 [jupyter.py:save_history():445] not saving jupyter history
2024-02-23 15:36:14,787 INFO    MainThread:26316 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-23 15:36:14,787 INFO    MainThread:26316 [wandb_run.py:_restore():2193] restore
2024-02-23 15:36:14,791 INFO    MainThread:26316 [wandb_run.py:_restore():2199] restore done
